version: '3'
services:
  metad:
    image: vesoft/nebula-metad:v3.5.0
    container_name: nebula-metad
    restart: always
    command:
      - --local_ip=metad
      - --meta_server_addrs=metad:9559
    ports:
      - "9559:9559"
      - "9560:9560"

  storaged:
    image: vesoft/nebula-storaged:v3.5.0
    container_name: nebula-storaged
    restart: always
    depends_on:
      - metad
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=storaged
    ports:
      - "9779:9779"

  graphd:
    image: vesoft/nebula-graphd:v3.5.0
    container_name: nebula-graphd
    restart: always
    depends_on:
      - metad
      - storaged
    command:
      - --meta_server_addrs=metad:9559
      - --local_ip=graphd
    ports:
      - "9669:9669"

  studio:
    image: vesoft/nebula-graph-studio:v3.5.0
    container_name: nebula-studio
    restart: always
    ports:
      - "7001:7001"